//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostnovaPromotion.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fine
    {
        public int Id { get; set; }
        public int IdStockConditions { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Sum { get; set; }
        public string Reason { get; set; }
    
        public virtual StockConditions StockConditions { get; set; }
    }
}
