//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostnovaPromotion.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockConditions
    {
        public StockConditions()
        {
            this.Fine = new HashSet<Fine>();
        }
    
        public int Id { get; set; }
        public int IdStock { get; set; }
        public int IdPromoter { get; set; }
        public int IdStatus { get; set; }
        public int WorkingHours { get; set; }
    
        public virtual ICollection<Fine> Fine { get; set; }
        public virtual Status Status { get; set; }
        public virtual Stock Stock { get; set; }
        public virtual User User { get; set; }
    }
}
