//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostnovaPromotion.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public Stock()
        {
            this.StockConditions = new HashSet<StockConditions>();
            this.SupervisorReport = new HashSet<SupervisorReport>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int IdType { get; set; }
        public int IdClient { get; set; }
        public string Place { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int QuantityPromoters { get; set; }
        public int IdManager { get; set; }
        public int IdStatus { get; set; }
    
        public virtual StockStatus StockStatus { get; set; }
        public virtual StockType StockType { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<StockConditions> StockConditions { get; set; }
        public virtual ICollection<SupervisorReport> SupervisorReport { get; set; }
    }
}
