//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostnovaPromotion.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupervisorReport
    {
        public int Id { get; set; }
        public int IdUser { get; set; }
        public int IdStock { get; set; }
        public System.DateTime CheckDate { get; set; }
        public string Comments { get; set; }
    
        public virtual Stock Stock { get; set; }
        public virtual User User { get; set; }
    }
}
