//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostnovaPromotion.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Stock = new HashSet<Stock>();
            this.StockConditions = new HashSet<StockConditions>();
            this.SupervisorReport = new HashSet<SupervisorReport>();
        }
    
        public int Id { get; set; }
        public string Fullname { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Passport_number { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public int IdRole { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual ICollection<Stock> Stock { get; set; }
        public virtual ICollection<StockConditions> StockConditions { get; set; }
        public virtual ICollection<SupervisorReport> SupervisorReport { get; set; }
    }
}
